apiVersion: v1
kind: Pod
metadata:
  name: blue-app
  labels:
    group: nature
spec:
  containers:
  - name: blue-app
    image: yoonjeong/blue-app:1.0
    env:
      - name: NODE_NAME
        valueFrom:
          fieldRef:
            fieldPath: spec.nodeName
      - name: NAMESPACE
        valueFrom:
          fieldRef:
            fieldPath: metadata.namespace
      - name: POD_IP
        valueFrom:
          fieldRef:
            fieldPath: status.podIP
    ports:
      - containerPort: 8080
    resources:
      limits:
        memory: "64Mi"
        cpu: "50m"
