kind: Pod
apiVersion: v1
metadata:
  name: unhealthy
  labels:
    app: myapp
spec:
  containers:
    - name: unhealthy
      image: yoonjeong/unhealthy-app:1.0
      ports:
      - containerPort: 8080
      readinessProbe:
        exec:
          command:
          - ls
          - /var/ready
        initialDelaySeconds: 60
        periodSeconds: 5
        successThreshold: 1
        failureThreshold: 1
        timeoutSeconds: 10
      resources:
        limits:
          memory: 64Mi
          cpu: 50m